### ISSUE TITLE
2a. Identify datasets

### ISSUE THREAD

**Issue by bbest** [ioos-eco/ioos-eco.github.io#6]
## Milestone

Step 2a: Identify initial target data sets, both federal and external data sources that are key for creation of data products for sanctuary habitats and condition report questions (including IEA, IOOS, & MBON specific data sets). Report due.

Also shared more specifics 2019-01-31: 

> In a nutshell for the next update, I anticipate completing the following...

## Condition Report

- [ ] add bibliographic capabilities
- [ ] populate rest of report with markdown text and static images
- [ ] prototype a few interactive figures with dynamic data, based on these [image_priorities](https://docs.google.com/spreadsheets/d/10-66T_Uv3-3Rq5Hb-ljqsB72bpe3rT16dH4spPUuJXY/edit#gid=1018297546) JB populated
- [ ] turn on Travis for fetching latest data with each new commit and weekly
- [ ] add instructions for using prose.io for WYSIWIG editing of markdown text

## Infographics

- [ ] wrap r2d3 into function, possibly as htmlwidget
- [ ] develop popup modal functionality within new framework
- [ ] link rest of habitats with elements
- [ ] develop prototype storyboard with marine heat wave
